image: node:carbon

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            # Clone web repository
            - git clone https://dudumonstr@bitbucket.org/dudumonstr/testing.git
            - cd testing
            - git checkout master
            # Installing npm packages
            - cd testing
            - ssh -i id_rsa taralite@34.80.239.68 "rm -rf /home/taralite/testing/*"
            - tar -zc ./ | ssh taralite@34.80.239.68 "tar -zx -C /home/taralite/testing"
