image: node:carbon

pipelines:
  branches:
    master:
      -step:
        caches:
          - node
        script:
          # Clone web repository
          - git clone https://dudumonstr@bitbucket.org/dudumonstr/testing.git
          - cd testing
          - git checkout master
          # Installing npm packages
          - npm install
          # Run npm build
          - CI=false npm run build:dev
          # Deploy to remote server
          - cd dist
          - ssh taralite@35.198.223.212 "rm -rf /home/taralite/testing/*"
          - tar -zc ./ | ssh taralite@35.198.223.212 "tar -zx -C /home/taralite/testing"
