image: node:carbon

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - ssh -i /opt/atlassian/pipelines/agent/ssh/id_rsa taralite@34.80.239.68 'cd testing && git pull'
